pipeline {
    agent {
        node {
            label 'Agent'
        }
    }
    options {
        // timeout(time: 10, unit: 'SECONDS') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    environment {
        COURSE = "DevOps"
    }
    stages {
        stage('Init') { // This is build stage as example
            //when { branch 'main' } 
            steps{
                script {  //using scripts here is a hybrid approach
                    withAWS(region: 'us-east-1',credentials: 'aws-auth'){
                        sh '''
                            cd 30-sg-rules
                            terraform init
                        '''
                    }
                }
            }
        }
        stage('Plan'){ // This is a test stage
            steps {
                script {
                    withAWS(region: 'us-east-1',credentials: 'aws-auth'){
                        sh '''
                            cd 30-sg-rules
                            terraform plan
                        '''
                    }
                }
            }
        }
        stage('Deploy'){ // This is a deploy stage for practice
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            //     parameters {
            //         string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
            //     }
            steps {
                script {
                    withAWS(region: 'us-east-1',credentials: 'aws-auth'){
                        sh '''
                            cd 30-sg-rules
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }
    
    } 
        

    post {
        always {
            echo 'I will say hello again regardless of build result'
            cleanWs()
        }
        success {
            echo "I will run this if build is success"
        }
        // aborted {
        //     withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'SLACK_URL')]) {
        //             sh '''
        //             curl -X POST -H 'Content-type: application/json' \
        //             --data '{"text":"Build Failed ✅"}' \
        //             $SLACK_URL
        //             '''
        //     }
        // }
        changed {
            echo "I will run this if pipeline status is changed"
        }
    }
}

